import Navbar from '@/components/Navbar'
import { Providers } from '@/utils/providers'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Coffee4u',
  description: 'Generated by Aya',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Navbar/>
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
